# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  KAKAO_SEARCH_KEY: ${{ secrets.KAKAO_SEARCH_KEY }}
  NAVER_SEARCH_ID: ${{ secrets.NAVER_SEARCH_ID }}
  NAVER_SEARCH_SECRET: ${{ secrets.NAVER_SEARCH_SECRET }}
  GOOGLE_APPLICATION_CREDENTIALS : ${{ secrets.GCP_CREDENTIALS }}
  ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
  REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
  GCP_KEY: ${{ secrets.GCP_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'Set up JDK 17'
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 'Cache Gradle dependencies'
      uses: actions/cache@v2
      with:
        path: ~/see-realview/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: 'Build and Test'
      run: ./gradlew clean build
      working-directory: ./see-realview
      
    - name: 'Run Spring Boot App for 10 seconds'
      run: |
        ./gradlew bootRun &
        APP_PID=$!
        sleep 10
        kill $APP_PID
      continue-on-error: false
      working-directory: ./see-realview

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    # - name: Publish to GitHub Packages
    #   uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
    #   with:
    #     arguments: publish
    #   env:
    #     USERNAME: ${{ github.actor }}
    #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
